### ISSUE TITLE
Potential Intent: CRIME INCIDENT REPORTS

### ISSUE THREAD

**Issue by curranjm** [codeforboston/voiceapp311#10]
Dataset:
https://data.boston.gov/dataset/crime-incident-reports-august-2015-to-date-source-new-system/resource/12cb3883-56f5-47de-afa5-3b1cf61b257b

Find out crime incidents that happened on your street.

**Comment by jaumb** [comment]
You can assign this one to me unless one of you has already started working on it

**Comment by jaumb** [comment]
https://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude
