### ISSUE TITLE
Some different streets in Boston use same names, suggest differentiate through zip codes

### ISSUE THREAD

**Issue by alidaniell** [codeforboston/voiceapp311#100]
If this is a repeat of the issue mentioned with Tremont Street addresses, i apologize.  The Trash Schedules by Address data (CSV) available from data.boston.gov sometimes contains duplicate records for what seems to be the same address, and it is not clear which days are correct.  See for instance 50 Tremont St (T&R are Wednesday on one record and TH&TH for four other records, all 50 Tremont St) and 0 A St (F&F and TH&TH).  No doubt there are others.

Turns out that though the README.md section Notes on open data sources for Boston. says we are using trash schedules by address CSV, the trash day intent is going out to https://recollect.net/api to get the information

Suggest we find a way to determine the correct records and do not upload the incorrect records from the data that is pulled into the skill.

**Comment by alidaniell** [comment]
Boston contains some streets with the same names and different zip codes.  Thus, some street names in Boston are not unique.  When using the app powered by Recollect (https://www.boston.gov/trash-day-schedule), it is possible to specify different zip codes, which in some cases are on different trash schedules. For instance:
50 Washington Street, Boston 02129 (Wed trash day)
50 Washington Street, Boston 02121 (Mon trash day)
50 Tremont Street, Boston, 02129 (Wed trash day)
50 Tremont Street, Boston, 02135 (Thurs trash day)
1 Arcadia Street, Boston, 02119 (Friday trash day)
1 Arcadia Street, Boston, 02122 (Tues trash day) 

Perhaps, in cases like these where street names are not unique, Alexa could prompt the user for the zip code to help it choose the appropriate trash day.

**Comment by NorwayMaple** [comment]
Hi guys,

On my local repo I made some changes on my own branch that eliminate the need for street-address in address_utils.py by making changes to that file and google_maps_utils.py such that it now (in my branch) queries the Google Maps Find Place API (not used before) to get a correctly formatted address.  My rationale is that Google's systems could do the address parsing well enough that we wouldn't have to worry about it with a separate module.  This would make the task of the zip code much easier (among others), but I'm not sure if it makes sense for the project as a whole.  I can push my changes (on a branch called "abe") and you can let me know what you think?

Best,
Abe
