### ISSUE TITLE
Enhancement request for response to queries about Trash and Recycling pickup

### ISSUE THREAD

**Issue by alidaniell** [codeforboston/voiceapp311#101]
When an address has pickup days for trash and recycling that are different, the skill does not differentiate and reports information as if both trash and recycling will be picked up on both days.

For instance, 100 Union Park has Trash pickup on TF and recycling pickup on T.   When I ask when is recycling pickup Alexa responds that "Trash and recycling is picked up on Tuesday and Friday."  If the person put out recycling on Friday it would not be recycled.  It would be nice if Alexa could respond that Recycling pickup is on Tuesday.

**Comment by jmartini** [comment]
@alidaniell I am seeing 200 Union Park Street have recycling on both Tuesday and Friday when I search [here](https://www.boston.gov/trash-day-schedule). Did you find this info somewhere else?

**Comment by alidaniell** [comment]
It looks like I must have had it from an old City of Boston spreadsheet, though I don't remember.  Checking some other addresses from the spreadsheet that showed recycling collected on fewer days than trash, in each case, the current website shows recycling and trash are collected on the same days.  This issue can be closed.

If leaf and yard waste is ever included, it is often picked up on fewer days than trash and recycling, and would be a fine candidate for this enhancement. 100 Union Park St: Tr & Rec: Tu & Fri; Yard Waste: Tu

**Comment by thiteixeira** [comment]
@jmartini is this still an issue?

**Comment by jmartini** [comment]
Closing this. Doesn't seem to be an issue.
