### ISSUE TITLE
Update card text for intents

### ISSUE THREAD

**Issue by jmartini** [codeforboston/voiceapp311#109]
We have been ignoring the text displayed on cards, which are displayed on the Alexa app. See [here](https://developer.amazon.com/docs/custom-skills/include-a-card-in-your-skills-response.html) for more info.

We need to clean up this card text to properly represent the response sent back to Alexa.

**Comment by alidaniell** [comment]
The Alexa docs advise showing card text to provide information in response to a user request (not as a prompt to the user), and to keep it brief, among other things.  Use of cards should describe or enhance the voice interaction. Cards can't be searched or saved, and disappear on Fire TV once the next one comes along. This app is set up to provide Simple cards, which supply plain text (no image), and are included in the response the service sends back to Alexa.  We provide text for title and content.

Using cards for the details of the emergency parking lot would be useful for presentation on cards. At the moment some parking lot entries seem very long for a voice response.

I don't have access to Echo devices with screens, so output was checked in two online locations: Test tab at https://developer.amazon.com with Echo Show Display and Echo Spot Display checked, and Home tab of https;//alexa.amazon.com, where people can configure their Alexa devices. The Home tab at https://alexa.amazon.com shows the skill name at each response. The Show and Spot Display emulators only showed the skill name when no card was displayed, as when Alexa asks the user "What's your address?".
Lambda_function.py is currently set to provide card responses for mycity_response.output_speech. Card responses for title and content start with "Session Speechlet - ", which shows on the devices.  I removed these for user clarity.  The card also provides the mycity_request.intent_name from mycity_controller.py in the title (such as TrashDayIntent, GetAlertsIntent, etc), which might confuse users who don't know about intents. Titles were changed within individual intents to better match the card's function, such as "Trash Day", "City Alerts", "Snow Parking", "Address", and "Unhandled". I didn't change intent names in mycity_controller.py to reduce the chance of unintended consequences.

**Comment by alidaniell** [comment]
jmartini requested these changes:
Add card text for when asking for trash day and no address has been provided
Add card text for when asking for snow parking location and no address has been provided

Added mycity_response.output_speech and mycity_response.card_title  to request_user_address_response in user_address_intent.py.   Added card to mycity_response_to_platform function in lambda_function.py in dialog_directive response section.

**Comment by jmartini** [comment]
Closed with PR #124
