### ISSUE TITLE
Unexpected input exits user out of boston data skill with <Audio only response>- normal behavior?

### ISSUE THREAD

**Issue by alidaniell** [codeforboston/voiceapp311#114]
This may be normal behavior, but since I am not sure, this issue has been opened.
When user asks for something not handled by the intents, including not handled by unhandled_intent.py, Alexa shows \<Audio only response\>.  If the user then asks for something boston data skill expects such as trash day, the response shows they are no longer using the Boston Data skill.
Example:  
User: Boston Data
Alexa: Welcome to the Boston Public Services Skill.....
User: chicken recipe
Alexa: \<Audio only response\>
User: trash day
Alexa: Sorry, I don't know that one.

Boston Data skill's usual response to trash day is "you can tell me your address by saying "my address is",.. " so the response above seems to show they are no longer using the boston data skill.

To see unhandled_intent.py handle input, respond with "whatever","what up doe", "testing", or any of the other phrases configured in UnhandledIntent on the Build tab in developer.amazon.com.  Behavior is same - unexpected input seems to give \<Audio only response\> and exit user out of boston data skill.
User:  boston data
Alexa:  Welcome to the Boston Public Services skill. How can I help you?
User: testing
Alexa: I'm not sure what you're asking me. Please ask again.
User: what up doe
Alexa:  I'm not sure what you're asking me. Please ask again.
User:  ticks bite
Alexa: \<Audio only response\>
user:  what is my trash day
Alexa: No, Trash is not a calendar date.

It would be great if Boston Data skill could tell user "I didn't get it, please say your address or say Quit to leave the Boston Data skill" instead of exiting the skill silently.  Leaving the skill without saying goodbye seems awkward.

**Comment by curranjm** [comment]
@Joshhw implemented an "unhandled intent" intent that was supposed to catch stuff like this.

Since then, Amazon has rolled out the "fallback intent", which we should probably be using to handle invocations we don't have an intent for:
https://developer.amazon.com/blogs/alexa/post/c97f3bb7-9701-41e8-ac06-a3a44b9f1638/use-the-new-fallback-intent-to-respond-gracefully-to-unexpected-customer-requests

**Comment by jmartini** [comment]
Opened #178 for this improvement.
