### ISSUE TITLE
suggest add new sample utterance to TrashDayIntent in Build tab at developer.amazon.com

### ISSUE THREAD

**Issue by alidaniell** [codeforboston/voiceapp311#115]
I keep asking boston data skill when trash day**s** are, causing the skill to end suddenly because it  expects an utterance containing a singular day.  Maybe other users will do this too.   Could we please consider adding utterances with day**s** as well as day?

Behavior:
User: boston data
Alexa: Welcome to the Boston Public Services Skil...
User: what is my trash day
Alexa: What's your address?
user: My address is 10 beacon street
Alexa: Trash and recycling is picked up...
user; trash days
Alexa: \<Audio only response\>      (Skill ends)

**Comment by rongood** [comment]
If one goes to en_US.json file and goes to line 40 and change "day" to "days".
This fixed the problem.

                        "when is my trash day",
to 
                        "when is my trash days",

"name": "TrashDayIntent",
                    "slots": [],
                    "samples": [
                        "when is my trash days",
                        "when is garbage day",
                        "what day is recycling",

**Comment by jmartini** [comment]
Closed by #119
