### ISSUE TITLE
Group debug logging strings onto a single line in CloudWatch

### ISSUE THREAD

**Issue by jmartini** [codeforboston/voiceapp311#120]
A number of our debug statements get split across multiple top level lines in cloud watch:
![image](https://user-images.githubusercontent.com/4166486/43049678-93707d42-8dc9-11e8-98e5-162020ed3435.png)

We should figure out how to have these statements that come from a single place in our code be nested into a single statement in CloudWatch. The default visible text should let the person looking at the log know where the statement came from. If they are interested in the associated data, they can dig down with the arrow.

**Comment by curranjm** [comment]
Here it is with all the multiline logs collapsed into single cloudwatch lines. This is done by replacing `\n` with `\r`. I think there's a setting on the logger agent where you can tell it to group everything until it sees the next timestamp, but it wasn't clear to me how we access and configure the Lambda logger agent.

![screenshot from 2018-10-07 16-56-09](https://user-images.githubusercontent.com/8085559/46586828-f49ea700-ca51-11e8-9eed-d9f095f482fe.png)
