### ISSUE TITLE
Create a best practices procedure and guide for running MyCity locally

### ISSUE THREAD

**Issue by jmartini** [codeforboston/voiceapp311#122]
A number of people are having issues running MyCity locally. It would be good to have a guide:
- Explain how to set up a development environment
- Scripts to make python file import work correctly and consistently (see [SetupTools](https://setuptools.readthedocs.io/en/latest/))

**Comment by timtheguy** [comment]
Hi @jmartini, @thiteixeira - how does this differ from[ the documentation available in the Wiki](https://github.com/codeforboston/voiceapp311/wiki/Installation)? I was able to follow the guide and get up and running in about 45 minutes.

**Comment by thiteixeira** [comment]
documentation was expanded and moved to the [Wiki](../wiki)
