### ISSUE TITLE
Do not allow user to specify an address which is not in Boston

### ISSUE THREAD

**Issue by SKalmane** [codeforboston/voiceapp311#125]
As of now, for the snow emergency parking intent, the user can provide any address and we try to grab relevant information. For example, I tried the address 42 6th Avenue New York and it returned the following text - "The closest snow emergency parking location, Municipal Lot #002, is at 398 Market St Boston, MA. It is 209 mi away and should take you 3 hours 39 mins to drive there. The parking lot has 42 spaces when empty. There is no fee.". I think it wouldn't make sense for the user to provide an address which is not in Boston and this should be validated.

**Comment by bdubs1991** [comment]
I think this one is fixed.

There is a 42 6th avenue in boston ALONG with the one in new york.

The boston one returns a response but the new york one makes alexa say "I'm not sure what you are talking about"

**Comment by jmartini** [comment]
Marking as blocking certification. With the addition of geolocation and device address APIs, the testing requirements say we have to notify the user if the address isn't within the service area. See [Functional Testing 3.9, test 3](https://developer.amazon.com/docs/custom-skills/functional-testing-for-a-custom-skill.html?ref_=pe_1872010_141001310#cert-device-location-api)

**Comment by thiteixeira** [comment]
PR #281
