### ISSUE TITLE
Farmers Market Intent

### ISSUE THREAD

**Issue by thiteixeira** [codeforboston/voiceapp311#149]
Add farmers market intent to allow users to find the nearest farmer's market. For instance,
`where is the nearest farmer's market` or
`is there a farmer's market today`

Pull data from `https://services.arcgis.com/sFnw0xNflSi8J0uh/ArcGIS/rest/services/Farmers_Markets_and_Fresh_Trucks/FeatureServer/0`

**Comment by jmartini** [comment]
@thiteixeira how did you find this data? Is there a link on Boston's site? Looking at it, the last update was 6/2017. I wonder if we can consider this data reliable or not? It could just be that there have been no changes to farmers market day/times.

**Comment by thiteixeira** [comment]
Hi @jmartini 
You're right. I looked at the `https://data.boston.gov/` and couldn't find an updated version of the dataset. I got the URL above when I started working on the Food Truck intent (which I realized is also is outdated and not on the Boston Data website).
Can you ask the folks at the City of Boston for updated datasets, please?
