### ISSUE TITLE
Supermarket/Grocery store Intent

### ISSUE THREAD

**Issue by thiteixeira** [codeforboston/voiceapp311#152]
Find nearby grocery stores

Pull data from `https://services.arcgis.com/sFnw0xNflSi8J0uh/ArcGIS/rest/services/Supermarkets_GroceryStores/FeatureServer/0`

**Comment by ethanstrominger** [comment]
@eric-s-s and I are doing this as an exercise to learn how to implement intents. We don't yet know how far we will get, so we are not assigning it to ourselves. If you want to work on this issue, let us know as we can share code.

**Comment by thiteixeira** [comment]
Hi @ethanstrominger 
Do you have a branch for this? You can follow other pull requests, such as PR #190 to have a sense on what files to change

**Comment by timtheguy** [comment]
Hi @ethanstrominger - while I appreciate a learning exercise, could you help me to understand how this differs from [the 'nearby places' request capabilities ](https://www.amazon.com/gp/help/customer/display.html?ie=UTF8&nodeId=201960850) built-in to Alexa already?

It seems to me that proximity to establishments such as grocery stores is a global feature easily made available to users outside of the Boston area, whereas the purpose of this skill is to provide access to services for Boston residents.

**Comment by eric-s-s** [comment]
Hi @timtheguy . It doesn't seem to differ at all.  However, it has helped us understand what is going on in the project and will help us when we work on other things in the project.

**Comment by thiteixeira** [comment]
PR #236 solves this issue
