### ISSUE TITLE
Suggested edits to Wiki for "Deploying Your Skill, Command Line Tools" for Windows CMD shell users

### ISSUE THREAD

**Issue by alidaniell** [codeforboston/voiceapp311#158]
Could someone please look at these suggested edits for  "Deploying Your Skill, Command Line Tools" for Windows CMD shell users?  Are these workarounds for the Windows CMD shell the preferred way to fix the issues?
------------------------
pip install awscli --upgrade --user

Note for users of Windows CMD shell:

After installing awscli as above using pip, your system may not find aws when you run aws configure because aws is not in the existing path.  If you find this is the case, uninstall awscli and re-install it without the --user switch.

pip uninstall awscli
pip install awscli --upgrade

[Explanation: pip installed to C:\Users\[USER]\Appdata\Roaming\  instead of  
C:\Users\[USER]\AppData\Local\Python\Python36\Scripts\ when using the --user switch, which is bug in the pip version currently included with Anaconda,  see:  https://github.com/aws/aws-cli/issues/3181 .  You could add C:\Users\[USER]\Appdata\Roaming\ to path instead of reinstalling awscli to the expected location C:\Users\[USER]\AppData\Local\Python\Python36\Scripts\  Or you could upgrade pip versions and hope the latest version of pip has fixed the issue ]. 

09/11/18 - When using Python Virtual Environment (Python Venv), pip did not install aws using pip install awscli --upgrade --user.  Pip successfully installed aws with:  pip install awscli --upgrade 
No need to change wiki, just reporting.]
----------------------------------
npm install -g ask-cli

Note for users of Windows CMD shell:

When installing Amazon Skills Kit Command Line Interface, Windows CMD shell users may receive this message:
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe".
 If the component is not installed, either 1) install the Microsoft Windows SDK
 for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual
 Studio 2008.  [C:\Users\Ali\AppData\Roaming\npm\node_modules\ask-cli\node_modu
les\dtrace-provider\build\binding.sln]

If you receive the above MSBUILD message, installing windows-build-tools could be a quick fix for the issue. Installing windows-build-tools also installs Python v2.7, but does not change the default Python version.

npm install -g --production windows-build-tools 

Then, try installing the Amazon Skills Kit Command line Interface again.

[Alternatives: you could do as the error message suggests, which involves downloading many GB. Or, you could install 3+ GB using choco install vcbuildtools.  Doing npm install -g --production windows-build-tools installs a few MB and is the quickest choice that I found]

**Comment by jmartini** [comment]
@alidaniell go ahead and apply these to the wiki

**Comment by alidaniell** [comment]
this was done.
