### ISSUE TITLE
Editeded wiki for "Setting Up a Python Virtual Environment" for Python Venv (Windows), please look over

### ISSUE THREAD

**Issue by alidaniell** [codeforboston/voiceapp311#162]
I added this to the "Setting Up a Python Virtual Environment" section of the wiki for Python Venv (Windows). Could someone please look it over for clarity and correctness? 

Download Python Venv. Follow the installation instructions to install Python Venv to the Windows environment and learn more about using it. It's assumed that you are using Python version 3.

Then you can create your virtual environment, activate the environment to work, and deactivate when done.

# to create a new environment
python -m venv <dir-name>

# to activate and do work
<dir-name>\Scripts\activate.bat
Confirm your virtual environment is set up: Your prompt will show the name of your virtual environment in parentheses, and the path to the virtual environment's Scripts directory will precede the rest of your usual path.

# to deactivate when done
<dir-name>\Scripts\deactivate.bat

**Comment by jmartini** [comment]
This looks good to me @alidaniell . I'm going to close this issue.
