### ISSUE TITLE
Skill doesn't recognize 240 heath st

### ISSUE THREAD

**Issue by Joshhw** [codeforboston/voiceapp311#167]
to replicate:
1. Open boston info
2. ask "when is trash day"
3. respond with "240 heath st"
4. wait for failure.

**Comment by thiteixeira** [comment]
Hi @Joshhw 
Does it only happen with voice commands? I tested given written commands and it works.

**Comment by rongood** [comment]
I found it worked as a written test too.

**Comment by ankitacodes** [comment]
on the similar lines, skill doesn't seem to recognize the addresses where you say alphabet "O" instead of zero number.

refer to the attached screenshot
![5o1_boylston_street](https://user-images.githubusercontent.com/40376848/52322818-868ad200-29a8-11e9-9f80-4d15f1ef90db.png)

**Comment by thiteixeira** [comment]
@Joshhw should we close this issue?

**Comment by rongood** [comment]
I think we can.
Ronald Goodstein   On Wednesday, February 20, 2019, 1:06:27 PM EST, Thiago <notifications@github.com> wrote:  
 
 
@Joshhw should we close this issue?

**Comment by thiteixeira** [comment]
Please follow #125 and #126
