### ISSUE TITLE
Research WhereAmI application

### ISSUE THREAD

**Issue by jmartini** [codeforboston/voiceapp311#168]
The City of Brookline is interested in making information about from their WhereAmI web application (http://gisweb.brooklinema.gov/WhereAmI/) accessible from Alexa. Lets first do some research into the application and map out how this could look and how the interaction could go.

**Comment by curranjm** [comment]
It looks like the interaction for this will be a lot like what we have set up already. This uses

You give it an address and it returns the following information (in order of proximity where there are multiple results):
Bus Stops
Fire Stations
Libraries
Local Historic District
Post Offices
Police Station
Precinct (Vote)
Polling Places
School District
School Buffer Zone
T Stops
Trash Pickup
Zoning District

It should be well-suited to the framework we have in place. Address acquisition would be the same that we have for Boston, maybe with some Brookline validation. Intents would be the above list. Interaction would look something like:
user: What are the 3 closest bus stops?
alexa: What's your address?
user: 123 Some Street
alexa: The 3 closest bus stops are ...



Searching addresses provides possible addresses to choose from, so we might be able to use that. For example, the default search for 333 Washington St gets the following response:
```
{
  "spatialReference": {
    "wkid": 102100,
    "latestWkid": 3857
  },
  "candidates": [
    {
      "address": "333 WASHINGTON ST",
      "location": {
        "x": -7917110.5728258491,
        "y": 5211146.1664032871,
        "z": 0
      },
      "score": 100,
      "attributes": {
        "Loc_name": "Building",
        "Score": 100,
        "Match_addr": "333 WASHINGTON ST"
      }
    }
  ]
}
```

Once an address is selected, a number of queries are made. For example, this is the response to the post office query:
```
{
  "displayFieldName": "NAME",
  "fieldAliases": {
    "OBJECTID": "OBJECTID",
    "FACILITYID": "Facility Identifier",
    "NAME": "Name of Facility",
    "OWNER": "Owner Name",
    "OWNTYPE": "Owner Type",
    "SUBTYPEFIELD": "Subtype Field",
    "FEATURECODE": "Feature Code",
    "FULLADDR": "Full Address",
    "AGENCYURL": "Website",
    "OPERDAYS": "Operational Days",
    "OPERHOURS": "Operational Hours",
    "CONTACT": "Contact Name",
    "PHONE": "Phone",
    "EMAIL": "Email"
  },
  "geometryType": "esriGeometryPoint",
  "spatialReference": {
    "wkid": 102100,
    "latestWkid": 3857
  },
  "fields": [
    {
      "name": "OBJECTID",
      "type": "esriFieldTypeOID",
      "alias": "OBJECTID"
    },
    {
      "name": "FACILITYID",
      "type": "esriFieldTypeString",
      "alias": "Facility Identifier",
      "length": 50
    },
    {
      "name": "NAME",
      "type": "esriFieldTypeString",
      "alias": "Name of Facility",
      "length": 255
    },
    {
      "name": "OWNER",
      "type": "esriFieldTypeString",
      "alias": "Owner Name",
      "length": 50
    },
    {
      "name": "OWNTYPE",
      "type": "esriFieldTypeString",
      "alias": "Owner Type",
      "length": 50
    },
    {
      "name": "SUBTYPEFIELD",
      "type": "esriFieldTypeInteger",
      "alias": "Subtype Field"
    },
    {
      "name": "FEATURECODE",
      "type": "esriFieldTypeString",
      "alias": "Feature Code",
      "length": 100
    },
    {
      "name": "FULLADDR",
      "type": "esriFieldTypeString",
      "alias": "Full Address",
      "length": 250
    },
    {
      "name": "AGENCYURL",
      "type": "esriFieldTypeString",
      "alias": "Website",
      "length": 100
    },
    {
      "name": "OPERDAYS",
      "type": "esriFieldTypeString",
      "alias": "Operational Days",
      "length": 50
    },
    {
      "name": "OPERHOURS",
      "type": "esriFieldTypeString",
      "alias": "Operational Hours",
      "length": 50
    },
    {
      "name": "CONTACT",
      "type": "esriFieldTypeString",
      "alias": "Contact Name",
      "length": 50
    },
    {
      "name": "PHONE",
      "type": "esriFieldTypeString",
      "alias": "Phone",
      "length": 12
    },
    {
      "name": "EMAIL",
      "type": "esriFieldTypeString",
      "alias": "Email",
      "length": 100
    }
  ],
  "features": [
    {
      "attributes": {
        "OBJECTID": 1,
        "FACILITYID": null,
        "NAME": "Brookline Village",
        "OWNER": "United States Postal Service",
        "OWNTYPE": "Federal Government",
        "SUBTYPEFIELD": 790,
        "FEATURECODE": null,
        "FULLADDR": "207 Washington St, Brookline, MA02445",
        "AGENCYURL": "www.usps.com",
        "OPERDAYS": "Other",
        "OPERHOURS": "Other",
        "CONTACT": null,
        "PHONE": "800-275-8777",
        "EMAIL": null
      },
      "geometry": {
        "x": -7916831.8070811387,
        "y": 5210908.9608982317
      }
    },
    {
      "attributes": {
        "OBJECTID": 2,
        "FACILITYID": null,
        "NAME": "Coolidge Corner",
        "OWNER": "United States Postal Service",
        "OWNTYPE": "Federal Government",
        "SUBTYPEFIELD": 790,
        "FEATURECODE": null,
        "FULLADDR": "1295 Beacon St, Brookline, MA 02446",
        "AGENCYURL": "www.usps.com",
        "OPERDAYS": "Other",
        "OPERHOURS": "Other",
        "CONTACT": null,
        "PHONE": "800-275-8777",
        "EMAIL": null
      },
      "geometry": {
        "x": -7917010.7265536943,
        "y": 5212365.9572170787
      }
    }
  ]
}
```

**Comment by alidaniell** [comment]
A few quick thoughts on the form of the interactions:

* if users ask for police or fire department, Alexa should say you can't call the fire department or police through this app. Call 911 on your phone if there is an emergency.

The Brookline app has so many choices you might need a reminder to find out what you can say, maybe like this:
user: Alexa, open Brookline Info
Alexa: Welcome to Brookline Info.
Say "what are my choices" for a list of choices you can request.

user: what are my choices, 
        what are the choices, 
        tell me the choices, 
        tell me my choices, 
        what can I ask?

For the bus stops, I would argue that the relevant info is the location of bus stop, the route number of the bus, and to which town it is going.  It would be great to have the schedule but I don't see that in the app.

alexa: the 3 closest bus stops are:
 address, route, inbound/outbound town X to town Y

For libraries and post offices, alexa gives the address and  phone number.  I can't remember phone numbers well and maybe others are the same, so maybe alexa can be told to repeat the phone number if requested. Maybe after alexa gives the details, phone number last, alexa says 'to hear that number again, say "repeat phone" or "repeat number"'

Amazon has some visual products that work with alexa such as Echo Show. They are different sizes and have different resolutions.  In Boston Info displays the text of much of what alexa says on the echo show. Would it be better to show maps on anything with an address?

**Comment by jmartini** [comment]
Thanks for the info everyone! Repository has been created [here](https://github.com/codeforboston/BrooklineVoiceApp)

**Comment by jmartini** [comment]
API info:

Map Layers:
http://gisweb.brooklinema.gov/arcgis/rest/services/MyGov/GovernmentServices/MapServer
 
For geocoding/address search:
http://gisweb.brooklinema.gov/arcgis/rest/services/Composite_WhereAmI/GeocodeServer
