### ISSUE TITLE
documentation setup issue

### ISSUE THREAD

**Issue by eric-s-s** [codeforboston/voiceapp311#189]
in installation instruction:  part 2 step 10 - 

if `SLACK_WEBHOOKS_URL` AND `GOOGLE_MAPS_API_KEY` are not in the keys with at least a dummy value, it successfully builds but does not work. 

The documentation is not clear that these keys **must** be there even with a dummy value.

**Comment by eric-s-s** [comment]
#187

**Comment by kami619** [comment]
@jmartini I think this issue is also fixed with the merge on last Tuesday. please close this issue.

**Comment by jmartini** [comment]
Closed with #187
