### ISSUE TITLE
when we ask "whats the time/weather/traffic" in Boston Info Alexa app, we are getting a response for latest 311 reports intent

### ISSUE THREAD

**Issue by ankitacodes** [codeforboston/voiceapp311#205]
when we ask "whats the time/weather/traffic" in Boston Info Alexa app, we are getting a response for latest 311 reports

I was testing the app to see if the generic intents of Alexa are still retained while being in the Boston Info app, however for common questions like "Whats the Weather in Boston ? ", "Whats the Traffic in Boston ?", "Whats the Time in Boston ?" the app responds with the below response - related to a feature #166 

_"Here are the 3 latest three one one reports: There was a request at 10 Ledgebrook Rd for the Public Works Department to address Pick up Dead Animal. There was a request at 33-35 Locust St for the Inspectional Services to address Work w/out Permit. There was a request at INTERSECTION Washington St & Spring Ln for the Public Works Department to address Street Light Outages."_

The reason might be because of the utterances data set used to train this intent which are close to the "Whats the .... ".

It would be good to give either the generic correct responses or a generic failure exception messages, but as an End user I would not be expecting latest 311 incidents when I ask these kind of questions.

**Comment by jmartini** [comment]
This looks to be fixed with #179

**Comment by jmartini** [comment]
@ankitacodes can you check this out again with the latest changes?

**Comment by kami619** [comment]
this has been tested and works as expected.
