### ISSUE TITLE
Snow Emergency Intent removes address

### ISSUE THREAD

**Issue by thiteixeira** [codeforboston/voiceapp311#213]
**Description:**
The snow intent currently resets the user address.

**Steps to reproduce:**

1. Open Boston Info
2. Try any other intent (e.g. trash day)
3. Alexa will ask for your address (e.g. 220 Clarendon st)
4. Snow emergency (Alexa will say: there are no weather-related alerts)
5. Try trash day again. At this point, Alexa will ask for the user's address, which was already provided at step 3

This only happens with the snow emergency intent.

**Acceptance criteria:**
When asking for weather-related alerts then another intent, Alexa should not have to ask for the user's address again.

**Comment by rongood** [comment]
Was able to reproduce error.  It looks like there is supposed to be a        mycity_response.session_attributes = mycity_request.session_attributes in the code.

**Comment by jmartini** [comment]
Closed with #228
