### ISSUE TITLE
Deploy Tools Throwing Warning when Updating Interaction Model

### ISSUE THREAD

**Issue by A-Camp** [codeforboston/voiceapp311#216]
When using the ASK CLI to update the interaction model for the Alexa Skill a warning of `(node:9456) ExperimentalWarning: The fs.promises API is experimental` continually appears with each progress dot. Upload does NOT fail but we may want to address this to a) prevent confusion and b) prevent `deploy_tools.py` from becoming outdated or having issues in the future.

**Comment by jmartini** [comment]
I am no longer seeing this with the latest ASK CLI. Closing for now.
