### ISSUE TITLE
Trash Day intent example not being recognized

### ISSUE THREAD

**Issue by JPHaus** [codeforboston/voiceapp311#232]
**Bug:**
When saying “Alexa, ask Boston Info what my garbage day is.” it doesn't recognize it and returns the fallback intent instead.

**Steps to reproduce the behavior:**
1. Say “Alexa, ask Boston Info what my garbage day is.”

**Expected behavior**
Asks for my address and then returns the trash days for that address,

**Device:**
 - Amazon Echo Dot 2 gen

**Additional context**
This phrase comes from the readme and others along with myself have tried it multiple times but couldn't get it to work.

**Comment by thiteixeira** [comment]
@JPHaus I assume this is because it is not a valid utterance. You can try something like:
`ask boston info when are the garbage days at 290 congress street`

See a list [here](https://github.com/codeforboston/voiceapp311/blob/master/mycity/platforms/amazon/models/en_US.json)

**Comment by JPHaus** [comment]
@thiteixeira that's what I figured but wanted another set of eyes. If that's the case then the [README example](https://github.com/codeforboston/voiceapp311#find-out-your-trash-day) should be updated or perhaps it could be added to the model.

**Comment by jmartini** [comment]
Lets make sure this utterance work, it seems reasonable that users would ask that

**Comment by jmartini** [comment]
Closed with #234
