### ISSUE TITLE
Feedback intent: Error message: "Skill response was marked as failure"

### ISSUE THREAD

**Issue by BrutiAnteneh** [codeforboston/voiceapp311#238]
**Describe the bug**

Skill interrupts a user utterance that is responding to the FeedbackIntent speech prompt: "**In a few sentences or less, please describe the feature**"

![image](https://user-images.githubusercontent.com/33470951/57731457-a9dcb180-7668-11e9-85e5-945a3fde3893.png)

**To Reproduce**
1. Open the Alexa app on your smartphone
2. Give the invocation: Open boston info
3. Say "I have feedback for this skill."
4. Give confirmation to Alexa's speech prompts 
6. When you reach this speech prompt: "**In a few sentences or less, please describe the Feature**" Say "include traffic advisories to this skill"
7. See error:
  
![image](https://user-images.githubusercontent.com/33470951/57732699-a7c82200-766b-11e9-84fe-975875804c81.png)

**Smartphone (please complete the following information):**
 - Device: iPhone Xs Max
 - OS: [e.g. iOS12.2]
 - Alexa app version 2.2.274439

**Comment by jmartini** [comment]
This was an issue with the lambda function set up. Better error handling was added with #239
