### ISSUE TITLE
Snow parking intent returns error when using the Alexa device location

### ISSUE THREAD

**Issue by jmartini** [codeforboston/voiceapp311#250]
**Describe the bug**
An error or irrelevant response was found in your skill’s responses with regards to device location settings. Please make sure that all skill functionality dependent on the device location is relevant to the location set by the user.

**To Reproduce**
User: "Alexa, open boston info"
Skill: "Welcome to the Boston Info skill. You can ask for help at any time, and I'll let you know what information I can provide. How can I help you?"
User: "snow parking"
Skill: "There was a problem with the requested skill's response"

**Expected behavior**
Snow parking intent works correctly with an address provided by the Device Location API.

**Additional context**
Please note that the skill delivers and error response when a relevant address is provided in the Alexa app. 

Please see our [Submission Checklist](https://developer.amazon.com/docs/custom-skills/functional-testing-for-a-custom-skill.html?ref_=pe_1872010_141001310#cert-device-location-api) for guidance on Device Location API implementation.

**Comment by Joshhw** [comment]
I think this has to do with not having the ARC_GIS_CLIENT_ID in the lambda function.

**Comment by jmartini** [comment]
Closed by #252
