### ISSUE TITLE
Keep session open when app requests a valid address

### ISSUE THREAD

**Issue by jmartini** [codeforboston/voiceapp311#287]
**Is your feature request related to a problem? Please describe.**
When using the trash intent, and the user provides an invalid address, we tell them to try another address. At this point the session is closed, and the user needs to start from the beginning. It would be better to keep the session open and allow the user to continue from that point with a valid address.

**Describe the solution you'd like**
Keep the session open when the user provides an invalid address. Allow them to continue from that point.

**Comment by fords** [comment]
I want to resolve this issue.

**Comment by fords** [comment]
User should be able to provide address and get result without saying "Trash day" keyword  again.
