### ISSUE TITLE
Snow Parking - Do not allow user to specify an address which is not in Boston

### ISSUE THREAD

**Issue by jmartini** [codeforboston/voiceapp311#288]
**Describe the bug**
If users provide an address, have their device registered to an address, or are using geolocation from an address outside of Boston, we should let the user know they can only use the service inside of Boston.

**To Reproduce**
*User provided address:*
"Open Boston Info"
...
"Snow parking at 100 Main Street New York"

*Device Address*
Register your device with an address outside of Boston, like the above example
"Open Boston Info"
...
"Snow Parking"

*Geolocation*
Use Alexa on a device, such as your phone, when outside of Boston
"Open Boston Info"
...
"Snow Parking"

**Expected behavior**
In all the above cases, we should return a message to the user that they need to use an address inside of Boston.

**Comment by fords** [comment]
I will resolve this issue.

**Comment by jmartini** [comment]
Closed with #295
