### ISSUE TITLE
Break up long list of alerts provide by GetAlertsIntent

### ISSUE THREAD

**Issue by jmartini** [codeforboston/voiceapp311#316]
**Is your feature request related to a problem? Please describe.**
"Currently the skill reads all alerts which translates into about ~50secs of info. Due to their being so many alerts right now because of COVID, we want to highlight the types of alerts and let the user decide which they're interested in.

**Describe the solution you'd like**
Can we adjust the language to inform them of which alerts are available by title? Users can then ask for a specific one or say all."

**Example Interaction**

User | Ask Boston info if there are any alerts. [or a specific alert]
-- | --
Alexa | There are 8 current alerts affecting the following services: Street Cleaning, City Building Hours, City Dept Hours, Parking Meters, Tow Lot, Meal Sites for Youths, Restaurants and Bars, and City Construction.  Which one would you like to hear about? Or say, "all".
User | Parking Meters
Alexa | Residents with a valid resident parking permit sticker can park in a metered or two-hour parking space in their neighborhood without having to adhere to the time limit, or pay a meter fee.

**Comment by nachiappan1312** [comment]
I will take shot at this task.

**Comment by EndyPremier** [comment]
already working on that

**Comment by nachiappan1312** [comment]
> already working on that

@EndyPremier  okay you carry on with this issue, I will choose a different one.

**Comment by EndyPremier** [comment]
One thing I have to bring up is that any response from the user only saying what services - like "Parking Meter", "School Closed", or "All" - need to have carrier phrases like "I pick" or "I decide" because apparently Amazon full-on reject having full-sentence SearchQuery result without a carrier:
https://developer.amazon.com/en-US/docs/alexa/custom-skills/slot-type-reference.html#amazonsearchquery

Just letting on an update.

**Comment by jmartini** [comment]
@nachiappan1312 @EndyPremier Sorry for the confusion here, I'll make sure this is assigned to @EndyPremier.

**Comment by jmartini** [comment]
@EndyPremier have you considered using the [list type](https://developer.amazon.com/en-US/docs/alexa/custom-skills/slot-type-reference.html#list-types) instead? We could provide some of the known services as examples, but it looks like the slot will still take unspecified responses from the user:

> Although input to the slot type is weighted towards the values in the list, it is not constrained to just the items on the list. You can either perform validation and error checking in your own code, or define slot validation rules in your dialog model and then delegate the dialog to Alexa to prompt the user for acceptable values.

>
