### ISSUE TITLE
Street Cleaning

### ISSUE THREAD

**Issue by Rizz311** [codeforboston/voiceapp311#34]
Should be able to ask Alexa when the street cleaning is coming in my neighborhood

**Comment by Joshhw** [comment]
is this any different from the other street sweeping issue we're doing?

**Comment by Rizz311** [comment]
I'm sorry I got caught up at Resilient with a fellow that needed help I will be in next meet up on Tuesday

Sent from Yahoo Mail on Android 
 
  On Tue, Jan 16, 2018 at 9:21 PM, Joshua Decosta<notifications@github.com> wrote:   
is this any different from the other street sweeping issue we're doing?

**Comment by jmartini** [comment]
Closing this as duplicate of #5
