### ISSUE TITLE
Intent: Snow Emergency

### ISSUE THREAD

**Issue by jmartini** [codeforboston/voiceapp311#40]
User should be able to ask if there is currently a snow emergency in the city.

There is no API for this information, but it is posted at http://www.boston.gov/snow as a banner at the top of this page. We should be able to parse this page. For development, lets see if we can see how this works from the page source as well as https://github.com/CityOfBoston/boston.gov

**Comment by wesdrew** [comment]
This information is posted on the top of Boston.gov when there's a snow emergency. I added a line that scrapes this in get_alerts_intent.py that collects it. It should be the first part of the get_alerts_intent utterance (when it exists_

**Comment by curranjm** [comment]
Should we add functionality specific to a snow emergency? We can build it on top of the `get_alerts_intent` functionality and just determine whether the `get_alerts_intent` result contains anything about a snow emergency.

We could also look into whether or not there are any other means of getting consistent information about weather related emergency status.
