### ISSUE TITLE
Intent: City of Boston status

### ISSUE THREAD

**Issue by jmartini** [codeforboston/voiceapp311#43]
Some of the most common real time status updates have been provided by Boston at https://www.boston.gov/. These can be seen as icons with associated text towards the top of the page, with a minimum of 5 items, but sometimes more. 

We should have an intent to get these statuses. This could be reading all statuses or you could ask for a specific status update.

**Comment by wesdrew** [comment]
I've gotten some scraping code that uses a 3rd party library, BeautifulSoup. Anything I should do to push this code for review?
