### ISSUE TITLE
Street Sweeping Day Intent

### ISSUE THREAD

**Issue by curranjm** [codeforboston/voiceapp311#5]
Add an intent that returns the street sweeping days for the street currently stored in the session.

The relevant API is here:
https://data.boston.gov/dataset/street-sweeping-schedules/resource/9fdbdcad-67c8-4b23-b6ec-861e77d56227

We should discuss what to output for this. Options include:
* the time/day (e.g. "street sweeping is on the even side from 8am to 10am on the third Wednesday of the month")
* the actual date of the next street sweeping day (e.g. "The next street sweeping day is Wednesday, October 18th from 8am to 10am.")

We also might want to consider whether or not we have an interface into the basic Alexa functionality so that we could do something like, "Remind me the day before the next street sweeping."

**Comment by saratlingamarla** [comment]
I'll start working on this. Thanks for creating the issue @curranjm

**Comment by saratlingamarla** [comment]
The street sweeping datastore has streets split up into multiple stretches of road/blocks, for example Hudson Street is divided into two parts, these parts are identified by the intersecting streets at either end.
Please take a look at this [Map](https://www.google.com/maps/place/Hudson+St,+Boston,+MA+02111/@42.3487533,-71.0630437,17z/data=!3m1!4b1!4m5!3m4!1s0x89e37a79c2faeb39:0x4de4ad789f4b48a4!8m2!3d42.3487494!4d-71.0608497)  , to get an idea

**Comment by nthh** [comment]
Starting off with same street 

Possibly add feature to prompt the user if they parked on a different street.

things to consider
- Finding which segment the user lives on
- Finding which street sweepings occur within a distance of the user

**Comment by nthh** [comment]
New solution:

1. Geocode all street-from and street-to pairs
2. Find all cross streets within X mi of the user (or closest one, and maybe only on their street)
3. List the street cleanings for the segment(s)

**Comment by thiteixeira** [comment]
@jmartini isn't this issue deployed already?
