### ISSUE TITLE
Add Boston Food Truck intent

### ISSUE THREAD

**Issue by dstair** [codeforboston/voiceapp311#52]
One of the most visited pages on the City of Boston's website is the Food trucks page at https://www.boston.gov/departments/small-business-development/city-boston-food-trucks-schedule.

Add an Alexa intent which allows users who have already provided their address to ask questions such as:
- What food trucks are available for [lunch/dinner] near me?
- How far am I from the closest food truck location?

Sample Utterances:
  GetTruckList near {address}
  GetTruckLocations given {truckname}

Possible future functionality:
  GetTruckTweets

Narrow vertical stripe of functionality v0:
ASK: What are the food trucks nearest to me.
RETURN: Return food trucks at location nearest to you. Assume today. Assume lunch.

**Comment by thiteixeira** [comment]
Please follow PR #190
