### ISSUE TITLE
AMAZON.StopIntent vs AMAZON.CancelIntent

### ISSUE THREAD

**Issue by curranjm** [codeforboston/voiceapp311#6]
We know that these built-in intents are important to stop Alexa from looping and trying to process everything she hears as an address, but we need a better understanding of skill's workflow.

The stop intent is straightforward, but we should have a better idea of how to use cancel so that we can write a separate handler for it in lambda_function.py.

**Comment by Kly4** [comment]
Merge #21 fixes the issue.
