### ISSUE TITLE
Incorporate SSML tag capabilities

### ISSUE THREAD

**Issue by curranjm** [codeforboston/voiceapp311#60]
SSML stands for Speech Synthesis Markup Language and allows us to do stuff like make Alexa whisper, pause, etc.

Explore what we'd need to add to use this and whether or not there is an analog on other platforms.

https://developer.amazon.com/docs/custom-skills/speech-synthesis-markup-language-ssml-reference.html

**Comment by jmartini** [comment]
@Joshhw was this done with #333 ?

**Comment by Joshhw** [comment]
Yes #333 closes this.
