### ISSUE TITLE
alerts intent has no response script for when there are no alerts

### ISSUE THREAD

**Issue by curranjm** [codeforboston/voiceapp311#63]
Asking for alerts when there are no alerts gets a silent response.

Add logic to provide a response script when there are no alerts.

**Comment by wesdrew** [comment]
This was addressed in expand_testing pull request

**Comment by curranjm** [comment]
@wesdrew was there a reason this was reopened or are we good to get rid of it?

**Comment by wesdrew** [comment]
This is good to close
