### ISSUE TITLE
Look into automated testing for new intents

### ISSUE THREAD

**Issue by curranjm** [codeforboston/voiceapp311#7]
Hopefully at the very least we can set something up that uses the service simulator to check responses.

**Comment by Joshhw** [comment]
We currently don't have a proper way to test our alexa skill. [Some people](https://pythonprogramming.net/testing-deploying-alexa-skill-flask-ask-python-tutorial/) use flask-ask for this very feature. Someone should explore the implementation details in using this functionality.
