### ISSUE TITLE
Moving print statements in functions to a logger 

### ISSUE THREAD

**Issue by wesdrew** [codeforboston/voiceapp311#76]
We're tracing what our code is doing during execution of an intent using print statements. Is there a reason we can't move these statements to a [logger](https://docs.python.org/3/library/logging.html#module-logging)?

```
def execute_request(self, mycity_request):
        """
        Route the incoming request based on type (LaunchRequest, IntentRequest,
        etc.) The JSON body of the request is provided in the event parameter.
        """

        print(
            self.LOG_CLASS,
            '[method: main]',
            'MyCityRequestDataModel received:\n',
            str(mycity_request)
        )
```

**Comment by curranjm** [comment]
Python's documentation says:

> Task you want to perform : Display console output for ordinary usage of a command line script or program
> The best tool for the task : print()

https://docs.python.org/3/howto/logging.html#logging-basic-tutorial

Would we be using the logger to standardize the way we send log statements to stdout to go to cloudwatch?

**Comment by Joshhw** [comment]
I'm with Jason, I'm wondering what the purpose of an explicit logger is in python.

**Comment by curranjm** [comment]
Looking at that a little more, I think it would make sense to use the logger -- everything we're logging so far would be at the `info` logging level.

From what I can see, the default level that it logs is `warning`, so we'd have to configure that for info, or log all of our diagnostic stuff at warning level (the former makes more sense to me).

**Comment by curranjm** [comment]
Update:
Per discussion at 5/22/18 hack night, we're going to go forward with this. We currently log by printing to stdout, which goes to cloudwatch, but in the future it will be useful to have the different logging levels that a logging package offers as we'll be less interested in logging all the `info` level feedback and want to focus just on `error`/`warning` level logs.

We'll still be sending the log messages to stdout, and per this article @jmartini found, we'll be able to filter the log messages in cloudwatch once we start adding this meta information to the log strings:
https://docs.aws.amazon.com/lambda/latest/dg/python-logging.html
