### ISSUE TITLE
Create common interface for intents that find closest X

### ISSUE THREAD

**Issue by wesdrew** [codeforboston/voiceapp311#80]
Code for intents that have the goal of finding the closest X have a common flow:

1. get information about X from some web resource

2. process information from resource into expected format

3. query Google Maps for the closest X to origin address 

4. format mycity_response.output_speech 

I was thinking an abstract Finder object with subclasses FinderCSV and FinderGIS might be easier for us to write new intents that are location focused. These classes can use the utils modules in utilities to do most of the work but the Finder objects could make our intent code more readable.

Here's a quick and dirty UML diagram:

![screenshot 2018-05-09 17 30 54](https://user-images.githubusercontent.com/14223487/39841076-9d567108-53af-11e8-9dd9-8fe38225a02a.png)

**Comment by SKalmane** [comment]
This makes sense. I was thinking about implementing the Polling Locations intent. It is super similar to the snow parking intent - we need to grab a list from the CSV file and find which amongst them is closest to our address. Abstracting out the logic and just calling the methods on a Finder object would make the process a lot easier.
