### ISSUE TITLE
Refactoring intents into intent objects

### ISSUE THREAD

**Issue by wesdrew** [codeforboston/voiceapp311#83]
There's code that's duplicated across our current intents (setting the title card, reprompt text). We could push that code into an IntentParent class and each subclass have its own logic for setting output_speech. Would people find this more confusing than how we're writing intents now?

**Comment by curranjm** [comment]
Is this still relevant? @wesdrew

**Comment by wesdrew** [comment]
I agree. I think it would make our code harder to understand and probably not worth the effort, at least with the number of intents we have. I've no problem closing this out

**Comment by curranjm** [comment]
Closing this given most recent discussion between @jmartini  and @wesdrew .
