### ISSUE TITLE
Potential intent: PUBLIC WORKS ACTIVE WORK ZONES

### ISSUE THREAD

**Issue by curranjm** [codeforboston/voiceapp311#9]
Dataset:
https://data.boston.gov/dataset/public-works-active-work-zones/resource/36fcf981-e414-4891-93ea-f5905cec46fc

Dataset can be used to alert user of work zones on a particular street.

**Comment by saratlingamarla** [comment]
I made a pull request, please take a look at it. Add the "hacktoberfest" label to this issue before merging the pull request.

**Comment by jmartini** [comment]
Won't do for now
