### ISSUE TITLE
Commuter Rail Intent

### ISSUE THREAD

**Issue by GreenGiraffe1** [codeforboston/voiceapp311#90]
Train schedules can change based on the season, day of week, and holidays.  This service will provide users departure and arrival times (and other relevant info) for any commuter rail trip in the Boston area.

MBTA’s API contains this information.  It can be found here:
[https://mbta.com/developers](https://mbta.com/developers)

The user will specify a departure and arrival location, and the service will return the next 2 train departure and arrival times.  Optionally, it will let the user add a time & date to the query.  If there’s currently a delay this service will notify the user and provide the expected times of departure & arrival (as calculated and provided by MBTA’s API).  It can also provide fare information.

**Comment by syip01** [comment]
I'd like to work on this if nobody objects.

**Comment by jmartini** [comment]
@GreenGiraffe1 are you currently working on this one?

**Comment by thiteixeira** [comment]
Won't do as it would be an MBTA app
